# Generated by Django 3.0.7 on 2020-10-24 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elements_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="percentage",
            field=models.FloatField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="element",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
